name: "Continuous Integration"
on:
  pull_request:
  push:
    branches:
      - master
      - 5.x
      - 4.0.x
      - 3.0.x
      - 2.0.x
      - 1.0.x
      - 0.2.x
jobs:
  smoke-check:
    name: "Tests with SQLite"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.4, 8.5 ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--ignore-platform-req=php+"
          dependency-versions: "${{ matrix.dependencies }}"
      - name: "Print SQLite version"
        run: >
          php -r 'printf("Testing with libsqlite version %s\n", (new PDO("sqlite::memory:"))->query("select sqlite_version()")->fetch()[0]);'
      - name: "Run Pest"
        run: "vendor/bin/pest"
  postgres:
    name: "Tests with PostgreSQL"
    runs-on: ubuntu-latest
    needs: smoke-check
    strategy:
      matrix:
        php: [ 8.4, 8.5 ]
        postgres-version:
          - "13"
          - "14"
    services:
      postgres:
        image: "postgres:${{ matrix.postgres-version }}"
        env:
          POSTGRES_PASSWORD: "postgres"
        options: >-
          --health-cmd "pg_isready"
        ports:
          - "5432:5432"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--ignore-platform-req=php+"
      - name: "Run Tests"
        env:
          DB_HOST: "localhost"
          DB_USER: "postgres"
          DB_PWD: "postgres"
          DB_SCHEMA: "postgres"
          DB_DRIVER: "postgres"
        run: "vendor/bin/pest"
  mariadb:
    name: "Tests with MariaDB"
    runs-on: ubuntu-latest
    needs: smoke-check
    strategy:
      matrix:
        php: [ 8.4, 8.5 ]
        mariadb-version:
          - "10.6"
          - "10.8"
    services:
      mariadb:
        image: "mariadb:${{ matrix.mariadb-version }}"
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_USER: "agp"
          MYSQL_PASSWORD: "agp"
          MYSQL_DATABASE: "agp"
        options: >-
          --health-cmd "mysqladmin ping --silent"
        ports:
          - "3306:3306"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "mysqli"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--ignore-platform-req=php+"
      - name: "Run Tests"
        env:
          DB_HOST: "127.0.0.1"
          DB_USER: "agp"
          DB_PWD: "agp"
          DB_SCHEMA: "agp"
          DB_DRIVER: "mysqli"
        run: "vendor/bin/pest"
  mysql:
    name: "Tests with MySQL"
    runs-on: ubuntu-latest
    needs: smoke-check
    strategy:
      matrix:
        php-version: [ 8.4, 8.5 ]
        mysql-version:
          - "8.0"
          - "9.0"
    services:
      mysql:
        image: "mysql:${{ matrix.mysql-version }}"
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_USER: "agp"
          MYSQL_PASSWORD: "agp"
          MYSQL_DATABASE: "agp"
        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=agp
          ${{ matrix.custom-entrypoint }}
        ports:
          - "3306:3306"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "mysqli"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--ignore-platform-req=php+"
      - name: "Run Tests"
        env:
          DB_HOST: "127.0.0.1"
          DB_USER: "agp"
          DB_PWD: "agp"
          DB_SCHEMA: "agp"
          DB_DRIVER: "mysqli"
        run: "vendor/bin/pest"

